// Auto-generated palette data — do not edit manually.
// Regenerate by running: pnpm --filter fornix-registry build:palettes
//
// Source: packages/fornix-registry/palettes/*.json

import type { Palette } from "./schemas/palette.js";

export const BUILTIN_PALETTES: ReadonlyArray<Palette> = [
  {
    schemaVersion: 1,
    name: "arctic",
    displayName: "Arctic",
    category: "nature",
    mode: "light",
    colors: {
      primary: "#0ea5e9",
      secondary: "#38bdf8",
      accent: "#6366f1",
      background: "#f0f9ff",
      foreground: "#0c4a6e",
    },
  },
  {
    schemaVersion: 1,
    name: "charcoal",
    displayName: "Charcoal",
    category: "dark",
    mode: "dark",
    colors: {
      primary: "#3b82f6",
      secondary: "#60a5fa",
      accent: "#f59e0b",
      background: "#1c1917",
      foreground: "#e7e5e4",
    },
  },
  {
    schemaVersion: 1,
    name: "copper",
    displayName: "Copper",
    category: "warm",
    mode: "dark",
    colors: {
      primary: "#b45309",
      secondary: "#d97706",
      accent: "#06b6d4",
      background: "#27272a",
      foreground: "#fef3c7",
    },
  },
  {
    schemaVersion: 1,
    name: "corporate-blue",
    displayName: "Corporate Blue",
    category: "professional",
    mode: "light",
    colors: {
      primary: "#1e40af",
      secondary: "#2563eb",
      accent: "#0d9488",
      background: "#f0f9ff",
      foreground: "#1e3a5f",
    },
  },
  {
    schemaVersion: 1,
    name: "cotton",
    displayName: "Cotton",
    category: "light",
    mode: "light",
    colors: {
      primary: "#7c3aed",
      secondary: "#8b5cf6",
      accent: "#10b981",
      background: "#fafaf9",
      foreground: "#1c1917",
    },
  },
  {
    schemaVersion: 1,
    name: "cream",
    displayName: "Cream",
    category: "light",
    mode: "light",
    colors: {
      primary: "#b45309",
      secondary: "#d97706",
      accent: "#059669",
      background: "#fffbeb",
      foreground: "#451a03",
    },
  },
  {
    schemaVersion: 1,
    name: "cyber-punk",
    displayName: "Cyber Punk",
    category: "vibrant",
    mode: "dark",
    colors: {
      primary: "#eab308",
      secondary: "#facc15",
      accent: "#ec4899",
      background: "#0a0a0a",
      foreground: "#fef9c3",
    },
  },
  {
    schemaVersion: 1,
    name: "deep-sea",
    displayName: "Deep Sea",
    category: "cool",
    mode: "dark",
    colors: {
      primary: "#06b6d4",
      secondary: "#22d3ee",
      accent: "#f97316",
      background: "#042f2e",
      foreground: "#ccfbf1",
    },
  },
  {
    schemaVersion: 1,
    name: "desert-sand",
    displayName: "Desert Sand",
    category: "nature",
    mode: "light",
    colors: {
      primary: "#c2410c",
      secondary: "#ea580c",
      accent: "#0d9488",
      background: "#fef3c7",
      foreground: "#431407",
    },
  },
  {
    schemaVersion: 1,
    name: "electric-violet",
    displayName: "Electric Violet",
    category: "vibrant",
    mode: "dark",
    colors: {
      primary: "#8b5cf6",
      secondary: "#a78bfa",
      accent: "#34d399",
      background: "#1e1b4b",
      foreground: "#ede9fe",
    },
  },
  {
    schemaVersion: 1,
    name: "ember",
    displayName: "Ember",
    category: "warm",
    mode: "dark",
    colors: {
      primary: "#ef4444",
      secondary: "#f87171",
      accent: "#fbbf24",
      background: "#1c1917",
      foreground: "#fef2f2",
    },
  },
  {
    schemaVersion: 1,
    name: "executive",
    displayName: "Executive",
    category: "professional",
    mode: "dark",
    colors: {
      primary: "#d4af37",
      secondary: "#f5d063",
      accent: "#4ade80",
      background: "#1a1a2e",
      foreground: "#eef2ff",
    },
  },
  {
    schemaVersion: 1,
    name: "fintech-dark",
    displayName: "Fintech Dark",
    category: "brand-inspired",
    mode: "dark",
    colors: {
      primary: "#10b981",
      secondary: "#34d399",
      accent: "#6366f1",
      background: "#0a0a0a",
      foreground: "#ecfdf5",
    },
  },
  {
    schemaVersion: 1,
    name: "forest",
    displayName: "Forest",
    category: "nature",
    mode: "dark",
    colors: {
      primary: "#22c55e",
      secondary: "#4ade80",
      accent: "#fbbf24",
      background: "#14532d",
      foreground: "#dcfce7",
    },
  },
  {
    schemaVersion: 1,
    name: "frost",
    displayName: "Frost",
    category: "cool",
    mode: "light",
    colors: {
      primary: "#6366f1",
      secondary: "#818cf8",
      accent: "#f43f5e",
      background: "#eef2ff",
      foreground: "#312e81",
    },
  },
  {
    schemaVersion: 1,
    name: "glacier",
    displayName: "Glacier",
    category: "cool",
    mode: "light",
    colors: {
      primary: "#0284c7",
      secondary: "#0ea5e9",
      accent: "#c026d3",
      background: "#ecfeff",
      foreground: "#164e63",
    },
  },
  {
    schemaVersion: 1,
    name: "golden-hour",
    displayName: "Golden Hour",
    category: "warm",
    mode: "light",
    colors: {
      primary: "#d97706",
      secondary: "#f59e0b",
      accent: "#be185d",
      background: "#fffbeb",
      foreground: "#451a03",
    },
  },
  {
    schemaVersion: 1,
    name: "health-clean",
    displayName: "Health Clean",
    category: "brand-inspired",
    mode: "light",
    colors: {
      primary: "#0891b2",
      secondary: "#06b6d4",
      accent: "#16a34a",
      background: "#f0fdfa",
      foreground: "#134e4a",
    },
  },
  {
    schemaVersion: 1,
    name: "luxury-gold",
    displayName: "Luxury Gold",
    category: "brand-inspired",
    mode: "dark",
    colors: {
      primary: "#d4af37",
      secondary: "#f5d063",
      accent: "#e11d48",
      background: "#0c0a09",
      foreground: "#fef9c3",
    },
  },
  {
    schemaVersion: 1,
    name: "midnight",
    displayName: "Midnight",
    category: "dark",
    mode: "dark",
    colors: {
      primary: "#6366f1",
      secondary: "#818cf8",
      accent: "#c084fc",
      background: "#0f172a",
      foreground: "#f8fafc",
    },
  },
  {
    schemaVersion: 1,
    name: "neon-tokyo",
    displayName: "Neon Tokyo",
    category: "vibrant",
    mode: "dark",
    colors: {
      primary: "#f43f5e",
      secondary: "#fb7185",
      accent: "#22d3ee",
      background: "#0c0a09",
      foreground: "#fef2f2",
    },
  },
  {
    schemaVersion: 1,
    name: "obsidian",
    displayName: "Obsidian",
    category: "dark",
    mode: "dark",
    colors: {
      primary: "#a855f7",
      secondary: "#7c3aed",
      accent: "#f472b6",
      background: "#09090b",
      foreground: "#fafafa",
    },
  },
  {
    schemaVersion: 1,
    name: "ocean-breeze",
    displayName: "Ocean Breeze",
    category: "nature",
    mode: "light",
    colors: {
      primary: "#0077b6",
      secondary: "#0096c7",
      accent: "#f4845f",
      background: "#caf0f8",
      foreground: "#023e8a",
    },
  },
  {
    schemaVersion: 1,
    name: "pearl",
    displayName: "Pearl",
    category: "light",
    mode: "light",
    colors: {
      primary: "#0891b2",
      secondary: "#06b6d4",
      accent: "#e11d48",
      background: "#f8fafc",
      foreground: "#0c4a6e",
    },
  },
  {
    schemaVersion: 1,
    name: "slate-modern",
    displayName: "Slate Modern",
    category: "professional",
    mode: "light",
    colors: {
      primary: "#475569",
      secondary: "#64748b",
      accent: "#0ea5e9",
      background: "#f8fafc",
      foreground: "#0f172a",
    },
  },
  {
    schemaVersion: 1,
    name: "snow",
    displayName: "Snow",
    category: "light",
    mode: "light",
    colors: {
      primary: "#2563eb",
      secondary: "#3b82f6",
      accent: "#f97316",
      background: "#ffffff",
      foreground: "#0f172a",
    },
  },
  {
    schemaVersion: 1,
    name: "startup-bold",
    displayName: "Startup Bold",
    category: "brand-inspired",
    mode: "light",
    colors: {
      primary: "#7c3aed",
      secondary: "#8b5cf6",
      accent: "#f97316",
      background: "#faf5ff",
      foreground: "#3b0764",
    },
  },
  {
    schemaVersion: 1,
    name: "storm",
    displayName: "Storm",
    category: "cool",
    mode: "dark",
    colors: {
      primary: "#64748b",
      secondary: "#94a3b8",
      accent: "#38bdf8",
      background: "#0f172a",
      foreground: "#cbd5e1",
    },
  },
  {
    schemaVersion: 1,
    name: "sunset-glow",
    displayName: "Sunset Glow",
    category: "vibrant",
    mode: "dark",
    colors: {
      primary: "#f97316",
      secondary: "#fb923c",
      accent: "#a855f7",
      background: "#18181b",
      foreground: "#fff7ed",
    },
  },
  {
    schemaVersion: 1,
    name: "terracotta",
    displayName: "Terracotta",
    category: "warm",
    mode: "light",
    colors: {
      primary: "#c2410c",
      secondary: "#dc2626",
      accent: "#65a30d",
      background: "#fdf2f8",
      foreground: "#431407",
    },
  },
  {
    schemaVersion: 1,
    name: "trust",
    displayName: "Trust",
    category: "professional",
    mode: "light",
    colors: {
      primary: "#0369a1",
      secondary: "#0284c7",
      accent: "#16a34a",
      background: "#f0fdfa",
      foreground: "#0c4a6e",
    },
  },
  {
    schemaVersion: 1,
    name: "void",
    displayName: "Void",
    category: "dark",
    mode: "dark",
    colors: {
      primary: "#14b8a6",
      secondary: "#2dd4bf",
      accent: "#f43f5e",
      background: "#020617",
      foreground: "#e2e8f0",
    },
  }
];
