import type { ResolvedConfig } from "../schemas/config.js";

type RecipeConfig = Omit<ResolvedConfig, "projectName" | "projectDir" | "createdWith">;

export const RECIPES: Record<string, RecipeConfig> = {
  saas: {
    renderMode: "server",
    deployTarget: "cloudflare",
    database: "d1",
    cssEngine: "tailwind",
    packageManager: "pnpm",
    blocks: [
      { name: "hero-video", variant: "default" },
      { name: "features-bento", variant: "default" },
      { name: "pricing-table", variant: "default" },
      { name: "faq-accordion", variant: "default" },
      { name: "footer-rich", variant: "default" },
      { name: "auth-better-auth", variant: "default" },
      { name: "db-d1", variant: "default" },
    ],
    locales: ["en"],
    defaultLocale: "en",
    palette: {
      preset: "obsidian",
      colors: {
        primary: "#818cf8",
        secondary: "#c084fc",
        accent: "#38bdf8",
        background: "#0f172a",
        foreground: "#f8fafc",
      },
    },
    themeSwitcher: false,
  },
  agency: {
    renderMode: "server",
    deployTarget: "cloudflare",
    database: "none",
    cssEngine: "tailwind",
    packageManager: "pnpm",
    blocks: [
      { name: "hero-gradient", variant: "default" },
      { name: "features-grid", variant: "default" },
      { name: "testimonials-carousel", variant: "default" },
      { name: "contact-form", variant: "default" },
      { name: "footer-rich", variant: "default" },
    ],
    locales: ["en"],
    defaultLocale: "en",
    palette: {
      preset: "ocean-breeze",
      colors: {
        primary: "#0ea5e9",
        secondary: "#38bdf8",
        accent: "#7dd3fc",
        background: "#0c4a6e",
        foreground: "#f0f9ff",
      },
    },
    themeSwitcher: true,
  },
  docs: {
    renderMode: "static",
    deployTarget: "cloudflare",
    database: "none",
    cssEngine: "tailwind",
    packageManager: "pnpm",
    blocks: [
      { name: "header-sticky", variant: "default" },
      { name: "docs-collection", variant: "default" },
      { name: "footer-minimal", variant: "default" },
    ],
    locales: ["en"],
    defaultLocale: "en",
    palette: {
      preset: "snow",
      colors: {
        primary: "#3b82f6",
        secondary: "#60a5fa",
        accent: "#93c5fd",
        background: "#ffffff",
        foreground: "#0f172a",
      },
    },
    themeSwitcher: false,
  },
  blog: {
    renderMode: "static",
    deployTarget: "cloudflare",
    database: "none",
    cssEngine: "tailwind",
    packageManager: "pnpm",
    blocks: [
      { name: "header-transparent", variant: "default" },
      { name: "hero-split", variant: "default" },
      { name: "blog-mdx", variant: "default" },
      { name: "cta-newsletter", variant: "default" },
      { name: "footer-rich", variant: "default" },
    ],
    locales: ["en"],
    defaultLocale: "en",
    palette: {
      preset: "corporate-blue",
      colors: {
        primary: "#1d4ed8",
        secondary: "#2563eb",
        accent: "#3b82f6",
        background: "#f8fafc",
        foreground: "#0f172a",
      },
    },
    themeSwitcher: false,
  },
  portfolio: {
    renderMode: "server",
    deployTarget: "cloudflare",
    database: "none",
    cssEngine: "tailwind",
    packageManager: "pnpm",
    blocks: [
      { name: "hero-gradient", variant: "default" },
      { name: "features-grid", variant: "default" },
      { name: "contact-form", variant: "default" },
      { name: "footer-minimal", variant: "default" },
    ],
    locales: ["en"],
    defaultLocale: "en",
    palette: {
      preset: "midnight",
      colors: {
        primary: "#6366f1",
        secondary: "#818cf8",
        accent: "#c084fc",
        background: "#0f172a",
        foreground: "#f8fafc",
      },
    },
    themeSwitcher: false,
  },
};
