/**
 * Post-scaffold hooks: actions that run AFTER the pure scaffold pipeline
 * writes files to disk.
 *
 * - Install dependencies (pnpm/npm/bun)
 * - git init + initial commit
 * - Generate CLAUDE.md with project-specific context
 * - Print success box with next steps
 */

import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";
import type { ResolvedConfig } from "../schemas/config.js";
import pc from "picocolors";

// ── Types ───────────────────────────────────────────────

export interface PostScaffoldInput {
  readonly config: ResolvedConfig;
  readonly resolvedBlockNames: ReadonlyArray<string>;
  readonly filesWritten: number;
  readonly verbose: boolean;
  readonly skipInstall?: boolean;
  readonly skipGit?: boolean;
}

export interface PostScaffoldCallbacks {
  readonly onLog: (message: string) => void;
  readonly onWarn: (message: string) => void;
}

// ── Public API ──────────────────────────────────────────

export function runPostScaffold(
  input: PostScaffoldInput,
  callbacks?: PostScaffoldCallbacks,
): void {
  const log = callbacks?.onLog ?? ((msg: string) => console.log(msg));
  const warn = callbacks?.onWarn ?? ((msg: string) => console.warn(msg));
  const { config, resolvedBlockNames, filesWritten, verbose } = input;
  const projectDir = config.projectDir;
  const projectName = basename(projectDir);

  // 1. Generate CLAUDE.md
  generateClaudeMd(projectDir, config, resolvedBlockNames);
  if (verbose) log(pc.dim("  created CLAUDE.md"));

  // 2. Install dependencies
  let installSuccess = false;
  if (!input.skipInstall) {
    installSuccess = installDependencies(projectDir, config.packageManager, verbose, log, warn);
  }

  // 3. Git init
  let gitSuccess = false;
  if (!input.skipGit) {
    gitSuccess = initGit(projectDir, verbose, log, warn);
  }

  // 4. Print success message
  log("");
  log(pc.green(pc.bold("✔ Project created successfully!")));
  log("");
  log(`  ${pc.bold("Project:")}  ${config.projectName}`);
  log(`  ${pc.bold("Dir:")}      ${projectDir}`);
  log(`  ${pc.bold("Render:")}   ${config.renderMode}`);
  log(`  ${pc.bold("Deploy:")}   ${config.deployTarget}`);
  log(`  ${pc.bold("CSS:")}      ${config.cssEngine}`);
  if (resolvedBlockNames.length > 0) {
    log(`  ${pc.bold("Blocks:")}   ${resolvedBlockNames.join(", ")}`);
  }
  if (config.locales.length > 1) {
    log(`  ${pc.bold("Locales:")}  ${config.locales.join(", ")} (default: ${config.defaultLocale})`);
  }
  if (config.palette.preset) {
    log(`  ${pc.bold("Palette:")}  ${config.palette.preset}`);
  }
  log(`  ${pc.bold("Files:")}    ${filesWritten} files written`);
  if (installSuccess) {
    log(`  ${pc.bold("Deps:")}     ${pc.green("installed")}`);
  }
  if (gitSuccess) {
    log(`  ${pc.bold("Git:")}      ${pc.green("initialized")}`);
  }
  log("");
  log(pc.dim("  Next steps:"));
  log(pc.dim(`    cd ${projectName}`));
  if (!installSuccess) {
    log(pc.dim(`    ${config.packageManager} install`));
  }
  log(pc.dim(`    ${config.packageManager} dev`));
  log(pc.dim(`    npx create-fornix add <block>`));
  log("");
}

// ── Dependency Installation ─────────────────────────────

function installDependencies(
  projectDir: string,
  packageManager: string,
  verbose: boolean,
  log: (msg: string) => void,
  warn: (msg: string) => void,
): boolean {
  try {
    log(pc.dim("  Installing dependencies..."));

    const cmd = `${packageManager} install`;
    execSync(cmd, {
      cwd: projectDir,
      stdio: verbose ? "inherit" : "pipe",
      timeout: 120_000,
    });

    return true;
  } catch {
    warn(pc.yellow("  ⚠ Could not install dependencies automatically."));
    warn(pc.dim(`    Run '${packageManager} install' manually.`));
    return false;
  }
}

// ── Git Init ────────────────────────────────────────────

function initGit(
  projectDir: string,
  verbose: boolean,
  log: (msg: string) => void,
  warn: (msg: string) => void,
): boolean {
  try {
    if (verbose) log(pc.dim("  Initializing git repository..."));

    execSync("git init", {
      cwd: projectDir,
      stdio: "pipe",
      timeout: 10_000,
    });

    execSync("git add -A", {
      cwd: projectDir,
      stdio: "pipe",
      timeout: 10_000,
    });

    execSync('git commit -m "Initial commit — scaffolded by Fornix"', {
      cwd: projectDir,
      stdio: "pipe",
      timeout: 10_000,
    });

    return true;
  } catch {
    warn(pc.yellow("  ⚠ Could not initialize git repository."));
    warn(pc.dim("    Run 'git init' manually."));
    return false;
  }
}

// ── CLAUDE.md Generation ────────────────────────────────

function generateClaudeMd(
  projectDir: string,
  config: ResolvedConfig,
  blockNames: ReadonlyArray<string>,
): void {
  const lines: string[] = [];

  lines.push("# CLAUDE.md");
  lines.push("");
  lines.push("Project context for AI assistants. Auto-generated by Fornix.");
  lines.push("");

  // Project overview
  lines.push("## Project Overview");
  lines.push("");
  lines.push(`- **Name:** ${config.projectName}`);
  lines.push(`- **Framework:** Astro`);
  lines.push(`- **Render mode:** ${config.renderMode}`);
  lines.push(`- **Deploy target:** ${config.deployTarget}`);
  lines.push(`- **CSS engine:** ${config.cssEngine}`);
  lines.push(`- **Package manager:** ${config.packageManager}`);
  lines.push("");

  // Installed blocks
  if (blockNames.length > 0) {
    lines.push("## Installed Blocks");
    lines.push("");
    for (const name of blockNames) {
      const variant = config.blocks.find((b) => b.name === name)?.variant ?? "default";
      lines.push(`- \`${name}\` (variant: ${variant})`);
    }
    lines.push("");
  }

  // i18n config
  if (config.locales.length > 1) {
    lines.push("## Internationalization");
    lines.push("");
    lines.push(`- **Locales:** ${config.locales.join(", ")}`);
    lines.push(`- **Default locale:** ${config.defaultLocale}`);
    lines.push("- Content is organized per locale in `src/content/{locale}/`");
    lines.push("- Routes are prefixed with `[locale]` parameter");
    lines.push("");
  }

  // Palette
  lines.push("## Styling");
  lines.push("");
  if (config.palette.preset) {
    lines.push(`- **Palette:** ${config.palette.preset}`);
  }
  lines.push("- Colors are defined as CSS custom properties in `src/styles/palettes/_current.css`");
  lines.push("- Use `var(--color-primary)`, `var(--color-secondary)`, etc. for theming");
  if (config.themeSwitcher) {
    lines.push("- **Theme switcher** is enabled — all registry palettes are available at runtime");
    lines.push("- Palette CSS files are in `src/styles/palettes/`");
  }
  lines.push("");

  // Key commands
  lines.push("## Key Commands");
  lines.push("");
  lines.push(`- \`${config.packageManager} dev\` — start development server`);
  lines.push(`- \`${config.packageManager} build\` — build for production`);
  lines.push("- `npx create-fornix add <block>` — add a new block");
  lines.push("- `npx create-fornix remove <block>` — remove a block");
  lines.push("- `npx create-fornix status` — show project configuration");
  lines.push("");

  // Project structure
  lines.push("## File Structure");
  lines.push("");
  lines.push("```");
  lines.push("src/");
  lines.push("├── components/sections/  ← block components");
  lines.push("├── content/              ← JSON/MD content (from blocks)");
  lines.push("├── layouts/              ← page layouts");
  lines.push("├── pages/                ← Astro pages (routes)");
  lines.push("├── styles/               ← CSS and palette files");
  if (config.renderMode === "server") {
    lines.push("├── middleware/            ← request middleware");
    lines.push("├── lib/                  ← server utilities");
    lines.push("├── pages/api/            ← API endpoints");
  }
  if (config.locales.length > 1) {
    lines.push("├── i18n/                 ← translation utilities");
  }
  lines.push("```");
  lines.push("");

  const content = lines.join("\n");
  writeFileSync(join(projectDir, "CLAUDE.md"), content, "utf-8");
}
